FROM ubuntu:18.04

RUN apt-get update && \
  apt-get upgrade -y && \
  rm -rf /var/lib/apt/lists/*

RUN export DEBIAN_FRONTEND=noninteractive

RUN echo "Europe/London" > /etc/timezone

RUN apt-get update && \
  apt-get install php-cli php-common php-memcached php-curl php-dom php-exif php-ftp php-gd php-iconv php-mbstring php-mysqli php-mysqlnd php-pdo php-posix php-soap php-zip php-ldap php-bcmath php-calendar php-gettext php-json php-apcu php-phar php-sockets php-tidy php-wddx php-xmlreader php-zip php-xsl php-opcache php-imagick php-ctype php-sqlite3 php-redis php-intl php-cli php-fpm -y && \
  rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
  apt-get install nginx -y && \
  rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
  apt-get install imagemagick -y && \
  rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
  apt-get install supervisor wget curl -y && \
  rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/nginx-uploads && chown www-data:www-data /var/nginx-uploads

RUN mkdir -p /var/cache/nginx/client_temp && \
  mkdir -p /var/cache/nginx/proxy_temp && \
  mkdir -p /var/cache/nginx/fastcgi_temp && \
  mkdir -p /var/cache/nginx/uwsgi_temp && \
  mkdir -p /var/cache/nginx/scgi_temp

RUN mkdir -p /src && \
  ln -s /etc/php/7.2/ /etc/php/php && \
  ln -s /usr/sbin/php-fpm7.2 /usr/bin/php-fpm

# Add Composer
RUN curl https://getcomposer.org/installer -o /tmp/composer-installer && php /tmp/composer-installer --install-dir=/usr/local/bin --filename=composer && rm -f /tmp/composer-installer

# Atatus
RUN wget https://s3.amazonaws.com/atatus-artifacts/atatus-php/downloads/atatus-php-1.6.1-x64-debian.tar.gz && tar -xzvf atatus-php-1.6.1-x64-debian.tar.gz && cd atatus-php-1.6.1-x64-debian && ./install.sh

# Atatus configurations
RUN sed -i -e 's#atatus.trace.response_time = 2000#atatus.trace.response_time = 1500#g'  /etc/php/php/fpm/conf.d/atatus.ini && \
  sed -i -e 's#atatus.collector.pidfile = "/var/run/atatus-php-collector.pid"#atatus.collector.pidfile = "/run/atatus-php-collector.pid"#g'  /etc/php/php/fpm/conf.d/atatus.ini && \
  sed -i -e 's#atatus.agent.log_level = "warning"#atatus.agent.log_level = "verbose_all"#g'  /etc/php/php/fpm/conf.d/atatus.ini && \
  sed -i -e 's#atatus.collector.log_level = "warning"#atatus.collector.log_level = "verbose_all"#g'  /etc/php/php/fpm/conf.d/atatus.ini && \
  sed -i -e 's#atatus.collector.connection = "/tmp/.atatus.sock"#atatus.collector.connection = "/run/atatus.sock"#g'  /etc/php/php/fpm/conf.d/atatus.ini

# Symlink the cli one
RUN rm -f /etc/php/php/cli/conf.d/atatus.ini && ln -s /etc/php/php/fpm/conf.d/atatus.ini /etc/php/php/cli/conf.d/atatus.ini
RUN rm -f /etc/php/php/cli/php.ini && ln -s /etc/php/php/fpm/php.ini /etc/php/php/cli/php.ini

# Supervisor
ADD conf/supervisord.conf /etc/supervisord.conf
ADD conf/supervisor.d /etc/supervisor.d
RUN mkdir -p /etc/supervisord-enabled && mkdir -p /etc/supervisord-worker

# Scripts
ADD scripts/start-web.sh /start-web.sh
RUN chmod 755 /start-web.sh
ADD scripts/start-worker.sh /start-worker.sh
RUN chmod 755 /start-worker.sh

ADD conf/nginx.conf /etc/nginx/nginx.conf

ADD conf/nginx-site.conf /etc/nginx/sites-enabled/site.conf

RUN rm -f /etc/nginx/sites-enabled/default 

# Test Nginx
RUN nginx -c /etc/nginx/nginx.conf -t

## PHP
ADD conf/php-fpm.conf /etc/php/php-fpm.conf
ADD conf/php.ini /etc/php/php/fpm/php.ini
ADD conf/php-www.conf /etc/php/php-fpm.d/www.conf

# Test PHP-FPM
RUN /usr/bin/php-fpm --fpm-config /etc/php/php-fpm.conf -t

# Cron
RUN mkdir -p /etc/cron.d

CMD ["/start-web.sh"]